# ¿Que son los tensores?

Son una generalización de los vectores.
- Un tensor de una dimención es un escalar.
- Un tensor de dos dimenciones es un vector.
- Un tensor de dos dimenciones es una matriz.

In [64]:
import torch
import numpy as np

### Inicializar un tensor

In [40]:
tensor_e = torch.tensor([[1,2,3],[4,5,6]])
tensor_e

tensor([[1, 2, 3],
        [4, 5, 6]])

### Inicializar un tensor con valores por defecto 0:

In [25]:
tensor_z = torch.zeros(2,2)
tensor_z

tensor([[0., 0.],
        [0., 0.]])

### Inicializar un tensor con valores por defecto de '1':
Recibe por parametro la dimensión.

torch.ones(filas, columnas)

In [11]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

### Inicializar un tensor con valores aleatorios:
El método debe tener la T mayúscula, ya que el método .tensor() espera cómo parametro los valores del tensor.

In [12]:
tensor_b = torch.Tensor(2,2)
tensor_b

tensor([[0.0000e+00, 0.0000e+00],
        [8.4207e-09, 4.5916e-41]])

### Método Uniform. 
El método uniform nos sirve para "mapear" los valores en un rango determinado.

Recibe por parametro: tensor.uniform_(rango_inferior, rango_superior).

Para usar este método debemos tener un tensor ya creado.

In [17]:
tensor_b.uniform_(0,1)
tensor_b

tensor([[0.7230, 0.5308],
        [0.2041, 0.3199]])

### Método Rand.
Con este método podemos inicializar un tensor con números entre 0 y 1.

Recibe por parámetro sus dimensiones.

In [19]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.2590, 0.5961],
        [0.0296, 0.1042]])

## Operaciones entre tensores.
#### Operaciones básicas:

In [30]:
resultSum = tensor_b + tensor_c
print(resultSum, "suma")
resultSum = tensor_b - tensor_c
print(resultSum, "resta")
resultSum = tensor_b * tensor_c
print(resultSum,"multiplicación")
resultSum = tensor_b / tensor_c
print(resultSum,"división")

tensor([[0.9819, 1.1269],
        [0.2337, 0.4241]]) suma
tensor([[ 0.4640, -0.0653],
        [ 0.1745,  0.2158]]) resta
tensor([[0.1872, 0.3164],
        [0.0060, 0.0333]]) multiplicación
tensor([[2.7918, 0.8904],
        [6.8914, 3.0719]]) división


#### Elevar a un exponente:

In [23]:
tensor_e.pow(2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

#### Sumar todos los componentes de un tensor:

In [24]:
tensor_e.pow(2).sum()

tensor(91)

#### Modulo
Se le aplica la operación a cada elemento del tensor.

In [31]:
tensor_e.fmod_(2)

tensor([[1, 0, 1],
        [0, 1, 0]])

### Transpuesta:

In [49]:
print(tensor_e)
print(tensor_e.t())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### Tomar los valores que cumplen cierta condición.
El método .where() nos sirve para formar un tensor donde sus elementos cumplan alguna condición.

Sintaxis: torch.where(condición, x,y) tensor x, será donde se evaluará la condición de lo contrario se tomará el valor que haya en la misma posición en y.

In [63]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
print(x)
print(torch.where(x > 0, x ,y))

tensor([[-1.4983,  1.1829],
        [ 1.3582, -0.9268],
        [-0.4399, -1.9582]])
tensor([[1.0000, 1.1829],
        [1.3582, 1.0000],
        [1.0000, 1.0000]])


## Tamaño o forma del tensor

In [32]:
tensor_e.shape

torch.Size([2, 3])

### Cambiar el tamaño de un tensor:

In [38]:
print(tensor_e, "original")
print(tensor_e.view(1,6))
print(tensor_e.view(3,2))
print(tensor_e.view(6,1))

tensor([[1, 0, 1],
        [0, 1, 0]]) original
tensor([[1, 0, 1, 0, 1, 0]])
tensor([[1, 0],
        [1, 0],
        [1, 0]])
tensor([[1],
        [0],
        [1],
        [0],
        [1],
        [0]])


### Acceder a una posición del tensor.
Se hace de la misma manera que se haría en una matriz.

In [42]:
print(tensor_e)
tensor_e[1][0]

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor(4)

## Almacenamiento en memoria.


In [43]:
tensor_e.storage()

 1
 2
 3
 4
 5
 6
[torch.LongStorage of size 6]

### Método stride.
#### Explicación tomada de un comentario de Platzi.
La idea detrás del stride es que se pueda acceder al elemento de manera física en memoria, más que del simple hecho de accederlo lógicamente ( por ejemplo points[1][0] ). Y es ahí donde stride me dice como hacerlo!. Esto es, que si por ejemplo quieres saber dónde está el numero 3 en el ejemplo que te pongo, tienes que multiplicar cada indice de donde se encuentra en el tensor con su respectivo stride de la dimensión y sumarlos todos juntos. En la imagen, la primera dimensión del tensor esta en azul y la segunda en rojo. Así pues, para obtener el el numero 3 de manera física se hace el cálculo stride:

1(fila del numero 3) X 2(dimensión stride de la fila) + 0(columna del numero 3)X1 (dimensión stride de la columna) = 2

El 2 significa que debes hacer dos saltos en memoria para obtener el numero 3

In [44]:
print(tensor_e, tensor_e.stride())

tensor([[1, 2, 3],
        [4, 5, 6]]) (3, 1)


### Cómo añadir una dimensión:
Este método recibe cómo parametro el tensor al cual se le añadirá la dimensión y la dimensión que se le quiere dar. 

In [62]:
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


### Transformar un Array de Numpy a un tensor


In [68]:
numpyArray = np.random.randn(2,2)
print(numpyArray)
print(torch.from_numpy(numpyArray))

[[-0.22663159 -2.29525184]
 [-1.40943663  0.68213589]]
tensor([[-0.2266, -2.2953],
        [-1.4094,  0.6821]], dtype=torch.float64)
